### ISSUE TITLE
entities[].state it works??

### ISSUE THREAD

**Issue by txusebe** [ExperienceLovelace/ha-floorplan#10]
im working in my floorplan and i want to change an image with several conditions of several entities.

i try something like this but i cant be able to make it works

service_data: |
          >
          if (entity.state === 'on') {
            if (entites['input_boolean.test'].state === 'on') {
              ...

**Comment by exetico** [comment]
Hi.

Please create question in the [Discussion](https://github.com/ExperienceLovelace/ha-floorplan/discussions)-area.

Also, please help us with helping you:
- Add your full YAML for Floorplan
- Add any attachments needed, if you have any
- Please explain what you would like to do, and what you're expecting to get as the result, too.

Thanks 👍

**Comment by pkozul** [comment]
Hi @txusebe Below is how you can use JavaScript to generate the `service_data`.

```
    - entity: sensor.ring_salon_battery
      state_action:
        - service: floorplan.text_set
          service_data: '${entity.state ? entity.state + "%" : "unknown"}'
        - service: floorplan.style_set
          service_data: |
            >
            var max = [195, 232, 141];
            var min = [240, 113, 120];
            var r = Math.floor(min[0] + ((max[0] - min[0]) * (entity.state / 100)));
            var g = Math.floor(min[1] + ((max[1] - min[1]) * (entity.state / 100)));
            var b = Math.floor(min[2] + ((max[2] - min[2]) * (entity.state / 100)));
            return `fill: rgb(${r}, ${g}, ${b})`; 
```

This is demonstrated in the [Ring](https://experiencelovelace.github.io/ha-floorplan/docs/example-ring/) example.
