### ISSUE TITLE
[FEATURE] Better error messages when a file is not found on the server

### ISSUE THREAD

**Issue by ali1234** [ExperienceLovelace/ha-floorplan#122]
When a file named in the configuration is missing from the server (404), the following log message is emitted:

```
27/06/2021, 16:51:50 ERROR fetchText/<@http://localhost:8123/hacsfiles/ha-floorplan/floorplan.js:65:2777 s@http://localhost:8123/hacsfiles/ha-floorplan/floorplan.js:65:734 
```

Notice that this message does not tell you which file is missing. It isn't even obvious that it is caused by a missing file. The only clue is that it has something to do with "fetchText".

Instead, the error message should clearly state what happened and the path of the missing file.

To reproduce the problem, set up the example configuration and then rename `/config/www/floorplan/examples/home/home.css` so that it will produce a 404 error when ha-floorplan tries to fetch it. (You will need to clear browser cache.)

**Comment by exetico** [comment]
Implemented and released in https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.26.

Thanks @pkozul :-)!
