### ISSUE TITLE
[FEATURE] Void service call

### ISSUE THREAD

**Issue by Sian-Lee-SA** [ExperienceLovelace/ha-floorplan#150]
**Is your feature request related to a problem? Please describe.**
Not a problem as such but more of a unified solution

**Describe the solution you'd like**
I like that you have the standard features to manipulate the elements via your own service calls being text. image, class etc. but these all expect a returned result. Simply put, it would be nice to have a void service call where I can manipulate the element etc. via direct code without returning anything. While this can still be accomplished by using set_style or so, I can add dom manipulating code and return an empty string but this comes across as "hacky".

**Describe alternatives you've considered**
Use a service call that expects something returned

**Illustrations and examples**

**Additional context**
I've admired your work and your custom card has made coding more fun and simpler in regards to the dynamic features. Kudos

**Comment by exetico** [comment]
Hi! Thanks for the feature request.

Is this some what like this, related to the `none` or `execute` suggestion?

https://github.com/ExperienceLovelace/ha-floorplan/discussions/181#discussioncomment-1932165

It sounds a bit like that.

If you're well known with JS+TS, we're always open for PR, just remember to stick to a readable and well-written solution 👍.

**Comment by exetico** [comment]
I'll close this due to inactivity. Fell free to reopen it.

**Comment by exetico** [comment]
Hi @Sian-Lee-SA 

If you're still using ha-floorplan, take a look at:
https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.34

**Comment by Sian-Lee-SA** [comment]
Just gave it a wirl and seems to work fine as a startup service. Will make more use of it down the track. Looks cleaner and easier to read. cheers
