### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luke321** [ExperienceLovelace/ha-floorplan#268]
**Describe the bug**
Floorplan preview in card configuration not working properly.
Everytime you edit a line, or even just press enter for a new blank line, another floorplan svg is added on the right in the preview until you cannot see what is going on.

It was working and I am pretty new to Home Assistant, I removed all other HACS packages but still have the problem.
My Yaml is generated from a python script because of the many duplicates.

**To Reproduce**
1. Go to code editor of floorplan card
2. place cursor at the end of yaml code
3. press enter
4. for each press, another svg picture gets addded

**Expected behavior**
Only one floorplan svg is show and mimics the code

**Screenshots**
![image](https://user-images.githubusercontent.com/3630619/202890541-715a2ee8-3851-404a-a136-eb3b478a1f94.png)

**Desktop (please complete the following information):**
 Windows with latest Chrome

**Share configuration**
Please share:
YAML: `type: custom:floorplan-card
full_height: true
config:
  image: /local/floorplan/Floorplan.svg
  stylesheet: /local/floorplan/home.css
  log_level: info
  console_log_level: info
  defaults:
    hover_action: hover-info
    hold_action: more-info
  rules:

          - entity: light.kuche_plug
            element: light.kuche_plug
            tap_action: toggle
            double_tap: more.info
            state_action:
             - service: floorplan.class_set
               service_data:
                 element: glow.kuche_plug
                 class: '${(entity.state === "on") ? "light-on" : "light-off"}'
        
          - entity: light.wohnzimmer_1
            element: light.wohnzimmer_1
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.wohnzimmer_1
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.wohnzimmer_1
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.wohnzimmer_2
            element: light.wohnzimmer_2
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.wohnzimmer_2
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.wohnzimmer_2
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.wohnzimmer_3
            element: light.wohnzimmer_3
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.wohnzimmer_3
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.wohnzimmer_3
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.wohnzimmer_panels
            element: light.wohnzimmer_panels
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.wohnzimmer_panels
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.wohnzimmer_panels
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.diele_panel
            element: light.diele_panel
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.diele_panel
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.diele_panel
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.flur_panel
            element: light.flur_panel
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.flur_panel
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.flur_panel
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.hobbyraum_panel
            element: light.hobbyraum_panel
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.hobbyraum_panel
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.hobbyraum_panel
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.schlafzimmer_enrave
            element: light.schlafzimmer_enrave
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.schlafzimmer_enrave
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.schlafzimmer_enrave
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.bad_xamento
            element: light.bad_xamento
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.bad_xamento
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.bad_xamento
                        persist_features: true
                        consolidate_entities: true
        
          - entity: light.wc_xamento
            element: light.wc_xamento
            state_action:
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    opacity: ${ entity.state === 'on' ? (entity.attributes.brightness
                    / 255) : '0' }
              - service: floorplan.style_set
                service_data:
                  element: glow.${entity.entity_id.substring(6)}
                  style: >-
                    fill: ${(entity.attributes.color_mode === ("xy" || !"color_temp")
                    ) ? "rgb(" + entity.attributes.rgb_color + ")" : "rgb(" +
                    util.color.kelvinToRGB(entity.attributes.color_temp_kelvin) + ")"}
            tap_action: toggle
            double_tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: light.wc_xamento
                  content:
                    type: horizontal-stack
                    cards:
                      - type: custom:light-entity-card
                        entity: light.wc_xamento
                        persist_features: true
                        consolidate_entities: true
                  
          - element: area.makergear
            state_action:
            - service: floorplan.text_set
              service_data:
                element: debug_text
                text: "test"
            - service: floorplan.style_set
              service_data:
                element: slider.makergear
                style: >
                  >  var start_time = new Date(states['sensor.octoprint_start_time_makergear'].state);
                  var end_time = new Date(states['sensor.octoprint_estimated_finish_time_makergear'].state);
                  var percentage = (Date.now() - start_time) / (end_time - start_time);
                  return `transform-origin: right center; transform-box:fill-box;
                  transform: scaleX(${percentage})`;        
            - service: floorplan.style_set
              service_data:
                element: printer.makergear
                style: >-
                  fill: ${(states['sensor.octoprint_current_state_makergear'].state === "Operational") ? "rgb(200,0,0)" : "rgb(0,0,100)"}  
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: makergear
                  content:
                    type: vertical-stack
                    cards:
                      - type: entity
                        entity: sensor.octoprint_estimated_finish_time_makergear
                      - type: picture-glance
                        entities:
                          - entity: sensor.octoprint_current_state_makergear
                            show_state: true
                          - entity: sensor.octoprint_job_percentage_makergear
                            show_state: true
                          - entity: sensor.octoprint_estimated_finish_time_makergear
                            show_state: true
                          - entity: sensor.octoprint_actual_tool0_temp_makergear
                            show_state: true
                          - entity: sensor.octoprint_actual_bed_temp_makergear
                            show_state: true
                        camera_image: camera.octoprint_camera_makergear             
                  
          - element: area.prusa_black
            state_action:
            - service: floorplan.text_set
              service_data:
                element: debug_text
                text: "test"
            - service: floorplan.style_set
              service_data:
                element: slider.prusa_black
                style: >
                  >  var start_time = new Date(states['sensor.octoprint_start_time_prusa_black'].state);
                  var end_time = new Date(states['sensor.octoprint_estimated_finish_time_prusa_black'].state);
                  var percentage = (Date.now() - start_time) / (end_time - start_time);
                  return `transform-origin: right center; transform-box:fill-box;
                  transform: scaleX(${percentage})`;        
            - service: floorplan.style_set
              service_data:
                element: printer.prusa_black
                style: >-
                  fill: ${(states['sensor.octoprint_current_state_prusa_black'].state === "Operational") ? "rgb(200,0,0)" : "rgb(0,0,100)"}  
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: prusa_black
                  content:
                    type: vertical-stack
                    cards:
                      - type: entity
                        entity: sensor.octoprint_estimated_finish_time_prusa_black
                      - type: picture-glance
                        entities:
                          - entity: sensor.octoprint_current_state_prusa_black
                            show_state: true
                          - entity: sensor.octoprint_job_percentage_prusa_black
                            show_state: true
                          - entity: sensor.octoprint_estimated_finish_time_prusa_black
                            show_state: true
                          - entity: sensor.octoprint_actual_tool0_temp_prusa_black
                            show_state: true
                          - entity: sensor.octoprint_actual_bed_temp_prusa_black
                            show_state: true
                        camera_image: camera.octoprint_camera_prusa_black             
                  
          - element: area.prusa_orange
            state_action:
            - service: floorplan.text_set
              service_data:
                element: debug_text
                text: "test"
            - service: floorplan.style_set
              service_data:
                element: slider.prusa_orange
                style: >
                  >  var start_time = new Date(states['sensor.octoprint_start_time_prusa_orange'].state);
                  var end_time = new Date(states['sensor.octoprint_estimated_finish_time_prusa_orange'].state);
                  var percentage = (Date.now() - start_time) / (end_time - start_time);
                  return `transform-origin: right center; transform-box:fill-box;
                  transform: scaleX(${percentage})`;        
            - service: floorplan.style_set
              service_data:
                element: printer.prusa_orange
                style: >-
                  fill: ${(states['sensor.octoprint_current_state_prusa_orange'].state === "Operational") ? "rgb(200,0,0)" : "rgb(0,0,100)"}  
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: prusa_orange
                  content:
                    type: vertical-stack
                    cards:
                      - type: entity
                        entity: sensor.octoprint_estimated_finish_time_prusa_orange
                      - type: picture-glance
                        entities:
                          - entity: sensor.octoprint_current_state_prusa_orange
                            show_state: true
                          - entity: sensor.octoprint_job_percentage_prusa_orange
                            show_state: true
                          - entity: sensor.octoprint_estimated_finish_time_prusa_orange
                            show_state: true
                          - entity: sensor.octoprint_actual_tool0_temp_prusa_orange
                            show_state: true
                          - entity: sensor.octoprint_actual_bed_temp_prusa_orange
                            show_state: true
                        camera_image: camera.octoprint_camera_prusa_orange             
        
`
- `CSS` -> default home.css
- SVG-file
- ![Floorplan](https://user-images.githubusercontent.com/3630619/202890624-d2d11586-1b8a-4b6a-a4df-edb115947c57.svg)

**Additional context**
As mentioned above, it was working for 2 days, but suddenly stopped after I added more stuff to the svg and yaml code.

**Comment by exetico** [comment]
We don't have preview support as is. 😊

**Comment by pkozul** [comment]
Hi @luke321 

Just as a test, how about if you remove all of the rules from the YAML? In other words, using the bare minimum YAML, does the issue still occur? Also, will be easier for us to try and reproduce.

**Comment by luke321** [comment]
Hi @pkozul 

Thanks for getting back to me, yes it does still occur. It's very odd, the preview in the code editor works fine, but only for the top svg. As soon as I edit anything in the editor field a new SVG gets appended.
Also as I mentioned, this behaviour is new and everything worked without a hinge in the beginning.

![image](https://user-images.githubusercontent.com/3630619/203719369-bfc9b7c6-77f6-46ea-b346-9ffcb5e1bab8.png)

**Comment by luke321** [comment]
@pkozul Yes i am running v1.0.34 and the latest problem, the issue persists across chrome, edge and the iOS app.

**Comment by OzGav** [comment]
Wouldn’t this likely be an issue with HA frontend and not floorplan?

@luke321 when you actually view your floorplan is it working correctly?

**Comment by luke321** [comment]
@OzGav You are probably right, the odd thing is that it started happen without any known update to me.
Yes everything works correctly after closing the Code Editor.

**Comment by maxwroc** [comment]
Same for me. Any update in the card config results in an additional floorplan rendered

**Comment by maxwroc** [comment]
Ok I think I know where is the problem. Will try to fix it and if the fix works I'll send PR

**Comment by RadekHvizdos** [comment]
Hello everyone

I’m still experiencing the same issue in version 1.0.35. Editing my floorplan is incredibly painful because duplicated images cause my browser to slow down and/or crash when I make too many changes at the same time. To work around this issue, I tend to add a character to my SVG file name path so that it fails to open and I can edit the YAML without any hassle.

@pkozul what is the status of PR #303? 

Thanks

**Comment by maxwroc** [comment]
@OzGav do you use the UI editor to add the card or pure yaml file/configuration? It happens only on UI editor preview pane - once the card is added on the page everything is fine.

If you look at the code it is clear that whenever the config changes the SVG element is appended to the HTML and it is never removed. Maybe I have missed some of the code which is doing it but I don't think so (if there is please point it to me - maybe there will be a better way to fix it than what I have done in my PR)

**Comment by OzGav** [comment]
Yeah I just use a text editor to edit the yaml file

**Comment by exetico** [comment]
@RadekHvizdos : I've requested him to take a look. Else I'll run through it, and release it as a pre-release. Have you tested the branch by yourself? :)

**Comment by RadekHvizdos** [comment]
> @RadekHvizdos : Did you have a chance to test it yourself?

Not yet. I will test it later this week. I am currently traveling.

**Comment by exetico** [comment]
That's fair. I'll give it a go.

Before:

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/37f8e808-ee71-4382-957a-47ad687f1e30)

Also thank you to @luke321 too. That's a great description of the bug, and how to reproduce it.

After:

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/bfce3ef5-d3a2-44df-a970-4223cddd9491)


Ignore the errors. I'll push it as part of 1.0.37.
