### ISSUE TITLE
[FEATURE] break lines handled by floorplan.text_set

### ISSUE THREAD

**Issue by zen2** [ExperienceLovelace/ha-floorplan#325]
**Is your feature request related to a problem? Please describe.**
I need to display a several lines text. This text is an HA entity state.

**Describe the solution you'd like**
I would like to have a way to place "new line" in HA entity state like "\n" or <br> ...

**Describe alternatives you've considered**
I've tried with CSS style to wrap text but I do not find a solution.

**Comment by OzGav** [comment]
This is how I have done it in the past. You can put two (or more) text objects in your floorplan and then use a [template sensor](https://www.home-assistant.io/integrations/template/) to hold the two (or more) sections of the longer state. The following would break up the sensor into a 10 character long string. You access the next ten characters by changing the `[0]` to `[1] `and so on. Change the 10 to whatever length you want.
`{{ (states.sensor.ha_uptime.state | wordwrap(10, true,"§")).split("§")[0] }}`

You could probably also do it with Javascript directly in the floorplan rule. Have a look here if want to do it that way https://stackoverflow.com/questions/10474992/split-a-javascript-string-into-fixed-length-pieces

**Comment by zen2** [comment]
> This is how I have done it in the past. You can put two (or more) text objects in your floorplan and then use a [template sensor](https://www.home-assistant.io/integrations/template/) to hold the two (or more) sections of the longer state. The following would break up the sensor into a 10 character long string. You access the next ten characters by changing the `[0]` to `[1] `and so on. Change the 10 to whatever length you want. `{{ (states.sensor.ha_uptime.state | wordwrap(10, true,"§")).split("§")[0] }}`
> 
> You could probably also do it with Javascript directly in the floorplan rule. Have a look here if want to do it that way https://stackoverflow.com/questions/10474992/split-a-javascript-string-into-fixed-length-pieces

I've different floorplan layers that are displayed in specific sensors conditions.
When such conditions are validated, using node-red,  I set a binary_sensor to unhide the corresponding floorplan layer and  I set another sensor dynamically with a list of sensors with node-red to fill the text area in this layer.

Before I get used to create one binary_sensor by element but it means:
- each element have a fixed position
- the panel/layer area need to be as big in size as maximum number of elements that can be potentially displayed.
- at each time I have to add a new sensor/element, I need to add it to the svg, create the binary sensor and add it to the floorplan yaml.

My purpose is to do it fully dynamically.

So your HA template solution is not dynamic since I still need to create HA sensors/svg element/floorplan yaml for a new sensor.

As far as I understand the JS solution could be dynamic by putting in floorplan.yaml something like this:

- a function multiline_text(text)
- a state-action like:
```
- entities:
  - sensor.multiline
  state_action:
  - action: call-service
    service: floorplan.text_set
    service_data: ${functions.multiline_text(entity.state)}
```

But I'm not sure that can work because it seems that floorplan.text_set encode special html characters returned by the function used by service_data. What do you think ?

**Comment by OzGav** [comment]
>  I have to add a new sensor/element, I need to add it to the svg, create the binary sensor and add it to the floorplan yaml

There may be a clever way to use Javascript and CSS to do what you want but what you describe above is the normal way floorplan is used. I will tag in @exetico as I am sure if there is a way to do what you want he will know.

**Comment by exetico** [comment]
Hi @zen2 

Could I kindly ask you to test this version?
https://raw.githubusercontent.com/ExperienceLovelace/ha-floorplan/feat/event_service%2Bhover_executions%2Btext_split_linebreakes/dist/floorplan.js

Please note that the test-version includes three different changes.

The service will now split `\n` into multiple `tspan` as the tspan elements doesn't allow line-breakes.

I know this will be a breaking feature, if we're going with this approach, so I'll do my best to remember that part.

Use the service like so:
```yaml
          state_action:
            - service: floorplan.text_set
              service_data:
                text: ${entity.state}
```

 I've decided to replace every `\n` with a new tspan element. Add two line-breaks, if more space is needed.

Kindly note that the tspan element will have a y axis offset. I've defaulted to `1em`, but you can adjust the spacing, by adding the `shift_y_axis` parameter as service data. It will impact all elements except the first one. I'm also using the x-position of the `text` element, if that's defined.

Use the shift_y_axis parameter like so:
```yaml
          state_action:
            - service: floorplan.text_set
              service_data:
                text: ${entity.state}
                shift_y_axis: 2em
```

Let me know if you're facing any problems.

References related to this request:
[Docs about the SVG > dy attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dy)
[Question related to linebreakes in a tspan element](https://stackoverflow.com/questions/49063695/how-to-insert-line-break-in-svg-tspan-element)

**Comment by zen2** [comment]
> Could I kindly ask you to test this version? https://raw.githubusercontent.com/ExperienceLovelace/ha-floorplan/feat/event_service%2Bhover_executions%2Btext_split_linebreakes/dist/floorplan.js
> 
> 
> Let me know if you're facing any problems. I'll tag @OzGav, too smile ...

Really thanks to implement this feature.
I understood that line break have to be implemented with tspan on my side too so that couldn't be done by CSS.

So I've tried your version and I got mitigated results:
- A: displayed text lost his svg position and get print at left/top corner like x=y=0.
- B: text with '\n' set by node-red is displayed on several lines perfectly on floorplan
     Note: `home-assistant/Developer Tools/States` display the state with '\n' stripped
                 but `{{ sensor.my_sensor.state }}` in `home-assistant/Developer Tools/Template` apply linebreaks correctly
- C: text with '\n' set by home-assistant using `Developer Tools/States/Set State` display one line containing '\n' on floorplan
     Note: `home-assistant/Developer Tools/States` or  `home-assistant/Developer Tools/Template` display both the state text string with '\n'

So far, for me it's working if I use node-red, need to know how to deal with home-assistant strange behaviour.
There is only the point A that need to be fixed.

I think we need to find a proper way to set a line break in a state with home assistant or to know the limitation in order to create related feature documentation to avoid users confusion.

About line breaks with home assistant templates:
https://community.home-assistant.io/t/force-newlines-or-linebreaks-in-a-template/6778/22

**Comment by exetico** [comment]
Could you share your SVG file?

The line-break things in HA is a Home Assistant related discussion, and nothing related to us.

I can for sure accept `<br>` too, as a work-around.

(Fell free to sent the SVG in a Email, if you dont like to share it in public)

**Comment by zen2** [comment]
> Could you share your SVG file? My test worked as expected, so it could be related to, how you've positioned your elements in the SVG file.
> (Fell free to sent the SVG in a Email, if you dont like to share it in public)

I've sent you my svg file by email with some explanations.
It is possible that svg layers visibility control from HA bring the offset problem.

**Comment by zen2** [comment]
> `ha-floorplan` uses the x position from the `text` object, and use that on the `tspan` element, and define a `dy` offset, to secure proper render disance.
> 
> Could you try move your `x` attribute from the `tspan`, to the `text ` element, instead? (Another note for the release notes, if we end up moving this into the main branch).

I use inkscape to design my svg and x/y attributes in tspan seems to come from inkscape if you select tspan instead of text object and I suspect that copy/paste and translate/transform operation can bring x/y parameter in tspan too because most of my text element are composed with tspan with x/y attributes.

So

**Comment by exetico** [comment]
I have tested the following cases:
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/2398d121-efce-445f-9bd6-864cf1887689)
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/89caebb5-3d29-4204-9381-fa53fb3c702a)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/33646c3f-ce10-4155-83b9-ea5a6c11b117)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/8f5111d3-e4cb-4ea2-82ba-f57e0f3a3749)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/1a72e94e-a3ad-49c3-99e2-58c74a465bbc)
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/8e35e519-02c8-4d7f-8834-8d4bc73beaf7)

Last one clearly doesnt work, but I just use it to confirm that the SVG updated on the way:
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/162359cc-7961-49dc-b72f-fcd53068cc20)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/c6c2a45a-db28-47fa-b157-b9528bda80ae)

It's tested with:
```
  - service: floorplan.text_set
    service_data:
      element: "sensor.bob1test"
      text: |
        > /* Use this function for both entities, to secure updates on both */
        return 'Bob is magic\nBob';
```

If a x and/or y attr are defined on the "text"-element, we'll do nothing. But if you only have x and/or y set on the tspan, we'll take the first tspan element within the text-element, and use the cords on the text el, before applying our offsets to the tspan.

I'll see if I can bake it into a release tonight, so we can get this closed

**Comment by exetico** [comment]
There's a pre-release ready for you @zen2 :  
https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.36 

Please let me know if that works for you.

**Comment by zen2** [comment]
> There's a pre-release ready for you @zen2 : https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.36
> Please let me know if that works for you.

Big thanks ! I have done some tests and it is working perfectly !
So now It's possible to create items list and display it.

Since we are at feature level, do you think it could be possible similarly to create easily a box around text as svg rect  ?
I'm thinking to define at svg level a rect with some properties and identify it by id like myelement_box and so inject position/size according to text size.
Actually I have a fixed rect size where I display a multi-lines text.
If the rect size could be sized dynamically with the text content that could let this feature a starting point for a real text dialog.

In fact I'm trying to use floorplan as my main interface and something that I wish is to be able to display and interact with some dialogue boxes. It is possible actually by using layer visibility as we can do to display different floors but it is working with fixed dialog boxes. Since we have now the possibility to display several text lines, do you see a way to do it by CSS (kind of text border) or is it needable to do it at svg level too ?

If you prefer to close this issue and have a new issue/feature, tell me it and I will create a new issue accordingly.
Anyway thanks a lot for this multi-lines text feature !

**Comment by exetico** [comment]
That's great news. I'm happy to hear that. Did you face any issues, after using this for a week? :) (or similar)

Our plugin are not really for manipulating/adding simple things as rects. If you think it's useful, fell free to create a separate feature request. I can't promise anything, but ha-floorplan are open source, so maybe other would find that interesting to implement (and create a pull request 😄 .

I'll close this on, and you pointed out yourself. IF you have faced any issues with the pre release in the last week, fell free to bump the issue.
