### ISSUE TITLE
Unable to download from inside HACS - Getting Started (1) | Add HACS & SVG-files and YAML entity mapping in Home Assistant

### ISSUE THREAD

**Issue by WuodDala** [ExperienceLovelace/ha-floorplan#326]
I have been trying to download HA-floorplan from inside HACS but it never completes the download (see image)
I have tried downloading other items and they complete fine. 

![Screenshot 2023-02-26 140422](https://user-images.githubusercontent.com/126223556/221434492-556849f7-911d-4855-b87a-72406992871d.png)

### Discussed in https://github.com/ExperienceLovelace/ha-floorplan/discussions/249

<div type='discussions-op-text'>

<sup>Originally posted by **exetico** October 17, 2022</sup>
### Getting Started video for ha-floorplan

Hi. Today is ... a new day for me.

Yesterday i planned and recorded a video on how to get started with ha-floorplan. It's done with Home Assistant OS, which are the easiest way to get started with Home Assistant.

[![image](https://user-images.githubusercontent.com/3549445/196247820-1954010a-5c52-4a58-b572-4edde9040575.png)](https://youtu.be/5ue9J4WG2a8)

https://youtu.be/5ue9J4WG2a8

I really hope that I'll find time to create more videos in the future, with more specific content - but I've received quite a few requests on how to get started with ha-floorplan, in the last couple of years.

_It's my first video in English and as a "teacher", but I've executed it the best I can, during a rainy sunday._

Attachments can be found here:
https://github.com/exetico/Home-Assistant_Attachments-for-YouTube/tree/main/1_Getting-Started-with-ha-floorplan

**Please hit the like-button on the video, and write a comment.** **Thanks!** 🙏

If you have any questions related to the video, fell free to drop them in this discussion :smiley:.

<hr>

### Links

Share your first frustrations about ha-floorplan here: https://github.com/ExperienceLovelace/ha-floorplan/discussions/247
Buy me a coffee ☕: https://www.buymeacoffee.com/coffeetoexetico</div>

**Comment by OzGav** [comment]
Has the ha-floorplan directory been created? Have you tried restarting HA?

**Comment by WuodDala** [comment]
Hi, Maybe i'm not as technical as needed to use this, but i've restarted HA multiple times.
What ha-floorplan directory are you referring to? I haven't been able to download if, was there something i need to do before going to download ha-floorplan? was just following the youtube video

**Comment by OzGav** [comment]
I mean the directory shown in your screenshot. Why do you think it hasn’t downloaded?

**Comment by exetico** [comment]
What version of Home Assistant are you using? And what about HACS? :) 

Have you tried manipulate some files in the meantime? If so, have you tried to start over?

I just removed ha-floorplan, and added it again, right no issues.

![image](https://user-images.githubusercontent.com/3549445/221590358-75881d41-0139-4e00-bb77-6a282ffd68b0.png)

![image](https://user-images.githubusercontent.com/3549445/221590458-bc49677e-6d2b-48e1-aa1b-00e782fef439.png)

Please create a Q&A instead:
https://github.com/ExperienceLovelace/ha-floorplan/discussions/new?category=q-a

This has (almost possible) nothing to do with ha-floorplan itself :smiley: !
