### ISSUE TITLE
[BUG] ha-floorplan breaks the automatic dashboard/view 

### ISSUE THREAD

**Issue by mdeweerd** [ExperienceLovelace/ha-floorplan#335]
You can also check the [discussion on the HA forum](https://community.home-assistant.io/t/wth-am-i-getting-this-error-when-changing-view-but-not-when-on-page-reload-when-the-view-is-selected/479856).

To reproduce this you need the default/automatic view and a floorplan view.

When you use the floorplan view before opening the default/automatic view in the same client page session, the following error appears:

![image](https://user-images.githubusercontent.com/1504752/235352921-1b0f8e68-8140-40ba-a51e-2a15f80d52e4.png)

It seems that this is because the floorplan view seems to add an entry to the hass.entities that has "*" as the key instead of having the entity_id as the key.

When the floorplan was not visited, this '*' key does not exist in 'entities' and the issue does not occur.  So the floorplan is adding the '*' entry somewhere while it should add entities["sensor.16996282-911ec145"]   (entities seems to be from hass.entities).

![image](https://user-images.githubusercontent.com/1504752/235352987-86d369bd-db0c-45cd-93e8-195efc974797.png)

**Comment by OzGav** [comment]
What version of HA floorplan are you using?

**Comment by mdeweerd** [comment]
I am on version 1.0.35, which is the latest AFAICS.

**Comment by mdeweerd** [comment]
BTW, I found this in the code (debugger):

```javascript
                    this.hass.states["*"] = {
                        entity_id: `sensor.${t}`,
                        state: "on",
                        last_changed: (new Date).toString(),
                        last_updated: (new Date).toString(),
                        attributes: {
                            device_class: "ha-floorplan",
                            friendly_name: "ha-floorplan - Floorplan for Home Assistant",
                            icon: "mdi:floor-plan",
                            assumed_state: !1,
                            hidden: !0
                        },
                        context: {}
                    },
```

Changing to
```javascript
                    this.hass.states[`sensor.${t}`] = {
```
possibly fixes the issue, but there may be a reason for the use of index "*" such as limiting the number of "virtual sensors" that seem to be defined this way to only 1.

Further there are other locations in the code that seem to rely on this (last line) that would require another means for identifying this special case:

```javascript
            getChangedEntities(t) {
                const e = new Set
                  , i = Object.keys(this.hass.states);
                for (const o of i)
                    if ("*" !== o || e.has(o)) {
```

**Comment by OzGav** [comment]
We had an issue in the past with the * entity so I thought this was fixed. Let me flag it with the devs @petarkozul @exetico

**Comment by exetico** [comment]
We are already aware of the issues related to this bug. Thank you for flagging it, in a issus 👍. Let's keep this open, until it's fixed.

Petar originally did the logics of that part of the code. So I'll need to find a bit of time, to see what it's related to, as of today, if there's any relations.

As you pointed out, there's a few areas of the code, which possibly should be rebaked a bit 😊.

**Comment by exetico** [comment]
Kindly check with: https://github.com/ExperienceLovelace/ha-floorplan/blob/dev/dist/floorplan.js

It's currently in the dev-branch.

**Comment by mdeweerd** [comment]
@exetico I've updated my floorplan.js and floorplan.js.gz with that version and I do not observe the issue anymore.
