### ISSUE TITLE
[BUG] Numbers are shifting up

### ISSUE THREAD

**Issue by Digitalhour** [ExperienceLovelace/ha-floorplan#339]
**Describe the bug**
When displaying numbers using **service: floorplan.text_set** numbers are shifted up a few pixels.

I am using  the following code to display volume level of my AVR. 
The volume digits are shifted up by about 4 px.

here is a basic image of whats happening 
https://i.imgur.com/eLZMmru.jpg

I am not using anything is CSS that would adjust the text! 
```javascript
                - entities:
                    - entity: media_player.home_theater_2
                      element: vol_dash
                  state_action:
                    action: call-service
                    service: floorplan.text_set
                    service_data: ${(entity.attributes.volume_level)}

**Comment by exetico** [comment]
What's caused the issue? Please share it with other 👍.
