### ISSUE TITLE
'floorplan.text_set' is broken since 1.0.37

### ISSUE THREAD

**Issue by RadekHvizdos** [ExperienceLovelace/ha-floorplan#355]
**Describe the bug**
'floorplan.text_set' is broken since 1.0.37. It now requires a newline (\n) character to be present to print even single lines.

**To Reproduce**
1. Edit a floorplan yaml to call floorplan.text_set with a oneline service_data:
```
state_action:
  - service: floorplan.text_set
    service_data: ANYTEXT
```
Kindy note that step 1 is if the YAML is edited in the GUI. See pictures in the end of the issue-report.

3. Observe there is no text visible on the floorplan
4. Append newline (\n) character to the floorplan (need to use js to print newlines):
```
state_action:
  - service: floorplan.text_set
    service_data: |
      >
        return ANYTEXT + '\n';
```

5. Text is now visible

**Expected behavior**
Single line text should be visible without using an explicit newline

**Images**
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/93f1de5e-fc7b-4903-8d5f-35bfad3b86c3)

**Comment by OzGav** [comment]
Can’t reproduce. It’s still works fine for me?

**Comment by exetico** [comment]
Thank you for the bug report.

Have you checked the release notes for 1.0.36 and 1.0.37?

https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.36

I've just tested this:
```yaml
        - service: floorplan.text_set
          service_data:
            text: |
              > /* Split text to two tspans*/
              return 'Multiline\nTSPAN-Print';
```

That work as expected.

The same goes for:
```yaml
          service_data: '${"Multiline\nTSPAN-Print2"}'
```

But I can confirm that the following doesn't work:
```yaml
# Doesnt work...
        - service: floorplan.text_set
          service_data: 'Multiline\nTSPAN-Print2'
```

As a end-user I'd expect that to work, too. That's the only solution where I face any issues.

However, I'm unable to reproduce the bug you're talking about.

```yaml
        - service: floorplan.text_set
          service_data: ANYTEXT
```

This logic works just fine here, and is rendered as expected.

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/5fea2025-e71b-49d9-91f0-419ca8ddfb5f)

Same goes for:
```yaml
        - service: floorplan.text_set
          service_data: |
            >
              return entity.state + '\n';
```

That works, too.

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/33f56a2e-cf71-49ac-99f6-51fea65f2109)

I need a full example with both a bit mor YAML, tested where you're able to:
1) Reproduce the error
2) Show the other text with new-line, which works as expected

And I'd need a sample SVG file too, to see if it's here where things get problematic. Kindly provide a stripped down version, to speed things up.

**Comment by OzGav** [comment]
You don’t need to wrap basic text in braces. 

So change `${“ANYTEXT1”}`to `“ANYTEXT1”`

**Comment by RadekHvizdos** [comment]
Hi @OzGav
Adding single or double quotes doesn't help, they get stripped from service_data when I click on save, and the text still isn't shown. Interestingly that now it doesn't need the newline in the js part, the quotes are enough for the text to be shown.

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/10856567/2dc50d15-320a-4714-b2c1-96f783bfe473)

I am using Edge on Windows 10, pretty standard setup. I can see the same behavior on my HA app on android.

**Comment by OzGav** [comment]
Your further fault finding may prove useful. Of interest I don’t edit via the UI so I don’t have the quotes stripped off. Not sure if that makes a difference at the end of the day but thought I would mention it. Thoughts @exetico

**Comment by RadekHvizdos** [comment]
Hi @exetico,

Have you had time to look at this issue already?

Thanks,

**Comment by exetico** [comment]
I'm unable to reproduce this. Have I misunderstood something?

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/3147bf47-1415-4f78-ab8b-f019db06bfda)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/c6968db5-8e31-433f-98e5-4c618dbd65a2)


This fails, as expected:
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/a17f969b-3b4c-4abe-b606-e4dba7caeaf0)
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/b239abb3-5101-4469-80c1-3549ec52e948)

Pay attention to `${'ANYTEXT1'}` vs `${“ANYTEXT1”}` (OzGav typed that, I'm not sure if that was an issue)

But changing that to `'`, and things works as expected, even in your SVG file:

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/4b067a2c-f002-4350-b7f6-65f1ae7eb358)

Another version of ha-floorplan are on the way. Let me know if it's still a problem in that one. I'll try and remember to link it here - else, check tomorrow, or saturday.
