### ISSUE TITLE
[BUG] t.replace is not a function setText

### ISSUE THREAD

**Issue by caesar1987sk** [ExperienceLovelace/ha-floorplan#375]
**Describe the bug**
I have input numbers and i want to display that number when is > 0 or empty string. 

**To Reproduce**
- entities:
            - input_number.vacuum_obyvacka_poradie
            - input_number.vacuum_kuchyna_poradie
            - input_number.vacuum_chodba_poradie
            - input_number.vacuum_chodbicka_poradie
            - input_number.vacuum_spalna_poradie
            - input_number.vacuum_filipko_izba_poradie
            - input_number.vacuum_miska_izba_poradie
          state_action:
            - service: floorplan.text_set
              service_data:
                text: |
                  >
                  var poradie = parseInt(parseFloat(entity.state));
                  if (poradie > 0){
                    return poradie;
                  }
                  return ""

In latests version im getting this error:
`Uncaught (in promise) TypeError: t.replace is not a function
    setText /hacsfiles/ha-floorplan/floorplan.js:54
    call Floorplan Service /hacsfiles/ha-floorplan/floorplan.js:131
    call Service /hacsfiles/ha-floorplan/floorplan.js:131
    handleActions /hacsfiles/ha-floorplan/floorplan.js:131
    handleEntity /hacsfiles/ha-floorplan/floorplan.js:131
    Ai /hacsfiles/ha-floorplan/floorplan.js:54
    Ai /hacsfiles/ha-floorplan/floorplan.js:54
    handleEntity /hacsfiles/ha-floorplan/floorplan.js:131
    handleEntities /hacsfiles/ha-floorplan/floorplan.js:131
    a /hacsfiles/ha-floorplan/floorplan.js:54
    promise callback*c /hacsfiles/ha-floorplan/floorplan.js:54`

When service data return number, its throwing error,
when it return string, its working as expected (e. g. when i add '+ "" ' that force js to convert it to string)

if (poradie > 0){
                    return poradie + "";
                  }

**Comment by caesar1987sk** [comment]
im not able to format that code properly here, so this is screenshot with formatted code
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/11236753/1a397b94-74a5-4ce7-8af6-cb2f84b31e5a)

this is part of that code when its working because of that conversion to string
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/11236753/8c310e95-b1f1-40de-aad5-c2bb447297cb)

**Comment by OzGav** [comment]
I will get back to you soon but just wanted to point out you are exposing your domain name in your first post….

**Comment by caesar1987sk** [comment]
Looks like that it caused by this replace
https://github.com/ExperienceLovelace/ha-floorplan/blob/3e362c05635187d891151c012b33c7e995dbb167/src/lib/utils.ts#L97C5-L97C5
but i dont k now why, because text should be string

**Comment by OzGav** [comment]
> i dont k now why, because text should be string

Correct but you are passing an `int` when the input number is greater than zero. Try this js shorthand (assuming your `input_number `is always a representation of an `int `otherwise use `parsefloat`):

```
              state_action:
                service: floorplan.text_set
                service_data: '${parseInt{entity.state) > 0 ? entity.state : ""}'
```

**Comment by caesar1987sk** [comment]
I will try when I will be back on pc.
But I saw in code that where setText function is called it's casted to string.

**Comment by OzGav** [comment]
Please refer to the docs instead of looking at the code. It is stated clearly there that the `text_set` service call requires a string.

**Comment by exetico** [comment]
This is clearly not a bug, as the service expects a string. That's simply cause HA normally return number and floats as strings, and we're following their take on the "state string"-type.
