### ISSUE TITLE
[FEATURE] Time loop replay

### ISSUE THREAD

**Issue by Maxouwell** [ExperienceLovelace/ha-floorplan#381]
**Is your feature request related to a problem? Please describe.**
I want to see the evolution of the temperature in my home in the last X hours, how the heat and the cold flows in the house

**Describe the solution you'd like**
Allow to add time options around the floor plan to launch a loop replay of the last hours, with each sensor/floor plan animation updating as time passes (time which should be displayed somewhere)

**Describe alternatives you've considered**
As far as I know the only alternative is a graph with all the temperature sensor, which go quickly messy.

**Illustrations and examples**
[Your example](https://experiencelovelace.github.io/ha-floorplan/docs/example-home/) is exactly what I had in mind, with a loop showing the evolution across time.
    
**Additional**
Floorplan seems amazing and I came across it while I was considering painfully learning how to do it myself.

**Comment by OzGav** [comment]
It’s an interesting idea but I can’t think how this would be achieved. ha-flooplan runs within HA and I don’t see any way to have this work in HA and a quick Google didn’t bring up any related discussions.
We have been looking at adding graphing capability but that hasn’t been finished yet

**Comment by Maxouwell** [comment]
Disclaimer: I don't have a clue how works Lovelace cards.

But if a graph card can show the evolution of a sensor on a span of X hours, why couldn't you get it ?
Once the history of all sensors is fetched, is it not just a ordering problem?
Looping a second at a time and inject it to floorplan to display the evolution across time.
I don't know how you do the animated example but it suspect it's not far from this.

**Comment by OzGav** [comment]
The examples are artificial constructs to show what is possible with representing current state. As I said the original developer of ha-floorplan has been looking at adding graphing capabilities so pulling in the state history is possible. The graphing capability leverages existing graphing libraries though. Coming up with a mechanism to be able to indicate which entity(ies) on a floorplan should be animated and for how long and to be able to indicate what time frame is being shown would be more difficult. But you have put it out there so we can see what other users think and if we find some dev time (which is in short supply) then this might get looked at.

**Comment by Maxouwell** [comment]
I looked into the code, and what I envision would be to rebuild the "timeframe" hass.states objects from the history API and time the calls to hassChanged to reflect the state at a given moment, replaying.

It would need to disable all user interaction though, and maybe regular hassChanged calls.
What do you think ?

**Comment by OzGav** [comment]
Sounds like a decent deviation from the existing functionality but maybe you could fork the project and build this yourself. Let me ping the devs though and see if they have time to comment @pkozul @exetico

**Comment by Maxouwell** [comment]
I didn't look in the examples code, but it's exactly what's your doing with a custom Hass simulator :D

**Comment by exetico** [comment]
I can't really se why a feature like this should fit into ha-floorplan, **but**, I'm ofc. open for a PR 😄 . It sounds like a very specific need, which I won't spend time on.

**Comment by exetico** [comment]
I'd kindly ask you to move the feature request to https://github.com/ExperienceLovelace/ha-floorplan/discussions/categories/hanging-feature-requests

Sadly GitHub does not allow me to simply migrate this to that category.
