### ISSUE TITLE
[BUG] Cannot find '*' in Home Assistant entities

### ISSUE THREAD

**Issue by exetico** [ExperienceLovelace/ha-floorplan#385]
**Describe the bug**
As part of the cleanup of the old `*` ha-floorplan entity in Home Assistant, it's not possible to use that, to trigger on every entity. It was not meant to be like that, at the time I did some changes a few releases back.

Right now, the user cannot use the `*` as a entity key, to listen for changes on every entity.

**To Reproduce**
1. Add a rule with `entity: '*'` as the selector for the entity
2. Save and see the log error

**Expected behavior**
We expect ha-floorplan to hook up to every entity change in the rule.e

**Screenshots**

<img width="670" alt="image" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/9792b7df-d477-4aad-8323-78d0ada19336">

**Additional context**
Are also part of ha-floorplan v. 1.0.40.

**Comment by OzGav** [comment]
Is there a way to solve that and not reintroduce the problem we previously had that led to its removal?

**Comment by joseaguardia** [comment]
Hi.

I have the same problem with HA 2024.04. I have done many tests and it always gives the same error that it cannot find the entity in the SVG.

Any solution or workaround?


Thanks

**Comment by exetico** [comment]
Sadly, no @joseaguardia, as I've not found time to work with it.

I'd like to ask: Did you just update Home Assistant, and faced the issue after the update, or maybe both ha-floorplan and Home Assistant? :-)

**Comment by joseaguardia** [comment]
> Sadly, no @joseaguardia, as I've not found time to work with it.
> 
> I'd like to ask: Did you just update Home Assistant, and faced the issue after the update, or maybe both ha-floorplan and Home Assistant? :-)


Both the component and HA are in the latest version. I hope you have time to solve it, the project looks very good

Regards

**Comment by OzGav** [comment]
@joseaguardia why do you need to monitor every entity?

**Comment by joseaguardia** [comment]
@OzGav I don't understand you well. I don't want to monitor all the entities, just some like the lights, as it appears in the manual

**Comment by OzGav** [comment]
Then you have added to an issue that is not relevant to you. Open a discussion in that area and we will help you there

**Comment by exetico** [comment]
Good catch @OzGav, I didn't think it was a XZ problem.

@joseaguardia Lets have a fresh discussion from you, with the problem you're facing. Try and make it clear, what you're trying to do, and **why** thats important/needed. Hopefully we're able to help you out. The solution you describes would be more than possible to do, without using `*`.

**Comment by exetico** [comment]
Solved in https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.45-beta.1
