### ISSUE TITLE
[QUESTION] floorplan.image_set causes image to disappear on firefox with layers

### ISSUE THREAD

**Issue by Skons** [ExperienceLovelace/ha-floorplan#388]
**Describe the bug**
When floorplan.image_set is used on an image in a hidden layer, on firefox the image will not be visible. In edge the image is in the expected place.

**To Reproduce**
Click on first in the floorplan

**Expected behavior**
I expect the image to be there. When the width and height are altered in the svg element, the image will be on the place where it should be.

**Screenshots**
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/13225002/937bc1ea-24c9-415f-b20b-ef6b20ad3755)

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/13225002/c391409d-2e58-496a-a573-3422ac1bb0a2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firerix
 - Version 120.0.1

**Share configuration**
https://filebin.net/a3okc55h1t1kkxfh

**Comment by OzGav** [comment]
Why do you think this is a floorplan issue and not a browser issue?

**Comment by Skons** [comment]
Well, it is floorplan that does the floorplan.image_set, so it was most logically for me to address the issue there.

**Comment by OzGav** [comment]
But it works fine in Edge? Have you tried any other browser, such as Chrome?

**Comment by Skons** [comment]
No, but i expect chrome to work due to having the same engine as edge. The HA app on ios works fine also, but FF is my main browser. Besides that, maybe the implementation is not as it should be, but edge is more foregiving in regards to the changes made by floorplan.image_set. If it is a browser bug, then this issue should be closed.

**Comment by Skons** [comment]
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/13225002/d240bd55-d6b3-4ff3-9d4a-f4ea301c67f1)
edge has the width and height properties, but they are gone on firefox.

**Comment by OzGav** [comment]
Googing this "firefox losing svg width and height" produces a bunch of results. 

As an option try using a PNG for your light on image.  It will obscure the light off image so you can leave that as it is.

**Comment by zen2** [comment]
The following ling can explain your current problem:
` https://stackoverflow.com/questions/76647524/svg-element-with-stroke-width-renders-differently-in-firefox-and-chrome`

What is happening if you remove the `stroke-width` of your rect in your svg ?
You don't need it anyway since the rect is transparent.
On Inkscape, you can use the XML editor to remove it easily.

**Comment by exetico** [comment]
As this is browser-related, I'd like the discussion to be moved to the Discussion section, but let's see how it goes with the troubleshooting. I don't see this as a ha-floorplan issue.

**Comment by Skons** [comment]
> The following ling can explain your current problem: ` https://stackoverflow.com/questions/76647524/svg-element-with-stroke-width-renders-differently-in-firefox-and-chrome`
> 
> What is happening if you remove the `stroke-width` of your rect in your svg ? You don't need it anyway since the rect is transparent. On Inkscape, you can use the XML editor to remove it easily.

Does not work...

> Googing this "firefox losing svg width and height" produces a bunch of results.
> 
> As an option try using a PNG for your light on image. It will obscure the light off image so you can leave that as it is.

Sounds like plan, thanks!

**Comment by Skons** [comment]
> Googing this "firefox losing svg width and height" produces a bunch of results.
> 
> As an option try using a PNG for your light on image. It will obscure the light off image so you can leave that as it is.

This works, but css with the x,y,width and height is needed. Thanks!

**Comment by OzGav** [comment]
Great. Please close this issue.
