### ISSUE TITLE
[BUG]my 'floorplan.text_set' is broken since 1.0.40

### ISSUE THREAD

**Issue by 602293544** [ExperienceLovelace/ha-floorplan#389]
![屏幕截图 2023-12-24 133235](https://github.com/ExperienceLovelace/ha-floorplan/assets/54359412/9cd5df3a-3e11-483f-8f86-0f5458990a78)

[floorplan.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/13760960/floorplan.zip)

**Comment by 602293544** [comment]
[Uploading floorplan.zip…]()

**Comment by exetico** [comment]
Take a look at the other text_set topics. Maybe you're missing something from these discussions. Also, please add more details.

Great floorplan, btw 😊👍.

**Comment by exetico** [comment]
I'll close this one next time I check (within a week or so), if no more details are provided. There's a plenty amount of topics related to text_set, including details in the release notes and docs, if you need details on how to handle line-breaks (if that's your problem).

**Comment by 602293544** [comment]
i'm sorry ,i don't know how to do.
can you give me some more information?

**Comment by OzGav** [comment]
You need to give us some more information about what is wrong.

**Comment by exetico** [comment]
I'm closing this one, as no more information has been provided.
