### ISSUE TITLE
`hold_action` doest not work on mobile devices

### ISSUE THREAD

**Issue by exetico** [ExperienceLovelace/ha-floorplan#8]
I just noticed that `hold_action` are not working on my phone.

I've confirmed it on both HA's Mobile App, and in the mobile browser - same story for both. I've tested for both things like toggle lights, both also browser mod services.

`hold_action` are working just fine on desktop-devices.

**Comment by exetico** [comment]
By using the debug tool in Chrome and Firefox (to simulate a device), my right-click menu are opening, if i make the `hold_action` on the mobile-device-like emulation :-) 

![image](https://user-images.githubusercontent.com/3549445/103476283-a3a6c600-4db4-11eb-8c73-9c53359ebc1e.png)

![image](https://user-images.githubusercontent.com/3549445/103476343-fe402200-4db4-11eb-839c-123336ebdd5f.png)

**Comment by txusebe** [comment]
same issue in v1.0.10 the `hold_action` doesn't work

**Comment by exetico** [comment]
Correct. It doesn't work on mobile devices right now. I've not found time to take a look at it.

_1.0.10 are the first public release. There's nothing changed, compared to the last 'pre' release_.
